version: 0.2

phases:
  install:
      runtime-versions:
          python: 3.x
  pre_build:
    commands:
      - cd cicd
      - chmod +x install-terraform.sh apply-terraform.sh
      - ./install-terraform.sh
  build:
    commands:
      - ./apply-terraform.sh
